### PR TITLE
CI: add Windows CI

### PR DESCRIPTION
**Pull request by compnerd**
Add coverage for Windows with Swift 5.5

### CODE REVIEW

**Comment by compnerd** [comment]
The CI failure is due to the 5.4 release of swift-syntax missing a change.  I've created apple/swift-syntax#283 to back port the fix for 5.4.  We will need to bump the dependency for Windows 5.4 support, but 5.5 should be fine.

CC: @mattt

**Comment by mattt** [comment]
@compnerd I'm really sorry if I wiped out your changes with https://github.com/SwiftDocOrg/SwiftSemantics/pull/15#event-4679025297. I wanted to rebase against latest `main` after #16, but unintentionally force-pushed some divergent, local history. 😓

**Comment by compnerd** [comment]
@mattt thanks for rebasing the branch, I don't think that anything really critical was lost.

**Comment by compnerd** [comment]
```
2021-05-03T17:15:13.0764957Z Test Suite 'All tests' started at 2021-05-03 17:15:13.072
2021-05-03T17:15:13.0765895Z Test Suite 'debug.xctest' started at 2021-05-03 17:15:13.075
2021-05-03T17:15:13.0766546Z Test Suite 'AssociatedTypeTests' started at 2021-05-03 17:15:13.075
2021-05-03T17:15:13.0767615Z Test Case 'AssociatedTypeTests.testAssociatedTypeDeclaration' started at 2021-05-03 17:15:13.075
2021-05-03T17:15:13.0773127Z <EXPR>:0: error: AssociatedTypeTests.testAssociatedTypeDeclaration : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0775198Z Test Case 'AssociatedTypeTests.testAssociatedTypeDeclaration' failed (0.0 seconds)
2021-05-03T17:15:13.0776398Z Test Suite 'AssociatedTypeTests' failed at 2021-05-03 17:15:13.075
2021-05-03T17:15:13.0777022Z 	 Executed 1 test, with 1 failure (1 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0777606Z Test Suite 'AttributeTests' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0778401Z Test Case 'AttributeTests.testAvailableAttribute' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0779910Z <EXPR>:0: error: AttributeTests.testAvailableAttribute : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0781351Z Test Case 'AttributeTests.testAvailableAttribute' failed (0.0 seconds)
2021-05-03T17:15:13.0782483Z Test Case 'AttributeTests.testPropertyWrapperAttribute' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0784136Z <EXPR>:0: error: AttributeTests.testPropertyWrapperAttribute : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0785774Z Test Case 'AttributeTests.testPropertyWrapperAttribute' failed (0.0 seconds)
2021-05-03T17:15:13.0786660Z Test Suite 'AttributeTests' failed at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0787243Z 	 Executed 2 tests, with 2 failures (2 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0788107Z Test Suite 'ConditionalCompilationBlockTests' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0789643Z Test Case 'ConditionalCompilationBlockTests.testConditionalCompilationBlock' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0792137Z <EXPR>:0: error: ConditionalCompilationBlockTests.testConditionalCompilationBlock : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0794595Z Test Case 'ConditionalCompilationBlockTests.testConditionalCompilationBlock' failed (0.0 seconds)
2021-05-03T17:15:13.0796064Z Test Suite 'ConditionalCompilationBlockTests' failed at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0796819Z 	 Executed 1 test, with 1 failure (1 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0797486Z Test Suite 'DeclarationCollectorTests' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0798605Z Test Case 'DeclarationCollectorTests.testDeclarationCollector' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0800529Z <EXPR>:0: error: DeclarationCollectorTests.testDeclarationCollector : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0802371Z Test Case 'DeclarationCollectorTests.testDeclarationCollector' failed (0.0 seconds)
2021-05-03T17:15:13.0803488Z Test Suite 'DeclarationCollectorTests' failed at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0804163Z 	 Executed 1 test, with 1 failure (1 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0804729Z Test Suite 'ExtensionTests' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0806368Z Test Case 'ExtensionTests.testExtensionDeclarationWithGenericRequirements' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0809288Z <EXPR>:0: error: ExtensionTests.testExtensionDeclarationWithGenericRequirements : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0812014Z Test Case 'ExtensionTests.testExtensionDeclarationWithGenericRequirements' failed (0.0 seconds)
2021-05-03T17:15:13.0814285Z Test Case 'ExtensionTests.testFunctionDeclarationWithinConstrainedExtension' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0817074Z <EXPR>:0: error: ExtensionTests.testFunctionDeclarationWithinConstrainedExtension : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0820630Z Test Case 'ExtensionTests.testFunctionDeclarationWithinConstrainedExtension' failed (0.0 seconds)
2021-05-03T17:15:13.0822686Z Test Case 'ExtensionTests.testFunctionDeclarationWithinExtension' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0824957Z <EXPR>:0: error: ExtensionTests.testFunctionDeclarationWithinExtension : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0827159Z Test Case 'ExtensionTests.testFunctionDeclarationWithinExtension' failed (0.0 seconds)
2021-05-03T17:15:13.0828953Z Test Case 'ExtensionTests.testinheritanceInConstrainedExtension' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0831209Z <EXPR>:0: error: ExtensionTests.testinheritanceInConstrainedExtension : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0833394Z Test Case 'ExtensionTests.testinheritanceInConstrainedExtension' failed (0.0 seconds)
2021-05-03T17:15:13.0834579Z Test Suite 'ExtensionTests' failed at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0835237Z 	 Executed 4 tests, with 4 failures (4 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0835870Z Test Suite 'FunctionTests' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0836879Z Test Case 'FunctionTests.testComplexFunctionDeclaration' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0838868Z <EXPR>:0: error: FunctionTests.testComplexFunctionDeclaration : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0840763Z Test Case 'FunctionTests.testComplexFunctionDeclaration' failed (0.0 seconds)
2021-05-03T17:15:13.0842230Z Test Case 'FunctionTests.testOperatorFunctionDeclarations' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0844178Z <EXPR>:0: error: FunctionTests.testOperatorFunctionDeclarations : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0846107Z Test Case 'FunctionTests.testOperatorFunctionDeclarations' failed (0.0 seconds)
2021-05-03T17:15:13.0847172Z Test Suite 'FunctionTests' failed at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0847813Z 	 Executed 2 tests, with 2 failures (2 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0848572Z Test Suite 'GenericRequirementTests' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0849995Z Test Case 'GenericRequirementTests.testGenericRequirementsInFunction' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0852433Z <EXPR>:0: error: GenericRequirementTests.testGenericRequirementsInFunction : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0854906Z Test Case 'GenericRequirementTests.testGenericRequirementsInFunction' failed (0.0 seconds)
2021-05-03T17:15:13.0856395Z Test Suite 'GenericRequirementTests' failed at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0857136Z 	 Executed 1 test, with 1 failure (1 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0857781Z Test Suite 'ImportTests' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0858730Z Test Case 'ImportTests.testComplexImportDeclaration' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0860555Z <EXPR>:0: error: ImportTests.testComplexImportDeclaration : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0862299Z Test Case 'ImportTests.testComplexImportDeclaration' failed (0.0 seconds)
2021-05-03T17:15:13.0863564Z Test Case 'ImportTests.testSimpleImportDeclaration' started at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0865708Z <EXPR>:0: error: ImportTests.testSimpleImportDeclaration : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0867576Z Test Case 'ImportTests.testSimpleImportDeclaration' failed (0.0 seconds)
2021-05-03T17:15:13.0868494Z Test Suite 'ImportTests' failed at 2021-05-03 17:15:13.076
2021-05-03T17:15:13.0869354Z 	 Executed 2 tests, with 2 failures (2 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0870006Z Test Suite 'InitializerTests' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0871261Z Test Case 'InitializerTests.testInitializerDeclaration' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0873236Z <EXPR>:0: error: InitializerTests.testInitializerDeclaration : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0874909Z Test Case 'InitializerTests.testInitializerDeclaration' failed (0.0 seconds)
2021-05-03T17:15:13.0875832Z Test Suite 'InitializerTests' failed at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0876446Z 	 Executed 1 test, with 1 failure (1 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0877047Z Test Suite 'ModifierTests' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0878165Z Test Case 'ModifierTests.testModifiersForPropertyDeclaration' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0880448Z <EXPR>:0: error: ModifierTests.testModifiersForPropertyDeclaration : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0882342Z Test Case 'ModifierTests.testModifiersForPropertyDeclaration' failed (0.0 seconds)
2021-05-03T17:15:13.0885655Z Test Suite 'ModifierTests' failed at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0886426Z 	 Executed 1 test, with 1 failure (1 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0887128Z Test Suite 'OperatorTests' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0888174Z Test Case 'OperatorTests.testSimpleOperatorDeclaration' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0890115Z <EXPR>:0: error: OperatorTests.testSimpleOperatorDeclaration : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0892011Z Test Case 'OperatorTests.testSimpleOperatorDeclaration' failed (0.0 seconds)
2021-05-03T17:15:13.0893057Z Test Suite 'OperatorTests' failed at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0893734Z 	 Executed 1 test, with 1 failure (1 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0894393Z Test Suite 'ProtocolTests' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0895315Z Test Case 'ProtocolTests.testProtocolDeclaration' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0896977Z <EXPR>:0: error: ProtocolTests.testProtocolDeclaration : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0898626Z Test Case 'ProtocolTests.testProtocolDeclaration' failed (0.0 seconds)
2021-05-03T17:15:13.0899671Z Test Suite 'ProtocolTests' failed at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0900329Z 	 Executed 1 test, with 1 failure (1 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0901018Z Test Suite 'StructureTests' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0902115Z Test Case 'StructureTests.testNestedStructureDeclarations' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0904096Z <EXPR>:0: error: StructureTests.testNestedStructureDeclarations : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0906242Z Test Case 'StructureTests.testNestedStructureDeclarations' failed (0.0 seconds)
2021-05-03T17:15:13.0908805Z Test Suite 'StructureTests' failed at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0909469Z 	 Executed 1 test, with 1 failure (1 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0910061Z Test Suite 'SubscriptTests' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0910874Z Test Case 'SubscriptTests.testSubscriptDeclaration' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0912401Z <EXPR>:0: error: SubscriptTests.testSubscriptDeclaration : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0913909Z Test Case 'SubscriptTests.testSubscriptDeclaration' failed (0.0 seconds)
2021-05-03T17:15:13.0914720Z Test Suite 'SubscriptTests' failed at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0915295Z 	 Executed 1 test, with 1 failure (1 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0915875Z Test Suite 'TypealiasTests' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0917107Z Test Case 'TypealiasTests.testTypealiasDeclarationsWithGenericParameter' started at 2021-05-03 17:15:13.079
2021-05-03T17:15:13.0919463Z <EXPR>:0: error: TypealiasTests.testTypealiasDeclarationsWithGenericParameter : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0921756Z Test Case 'TypealiasTests.testTypealiasDeclarationsWithGenericParameter' failed (0.001 seconds)
2021-05-03T17:15:13.0923696Z Test Case 'TypealiasTests.testTypealiasDeclarationsWithGenericRequirement' started at 2021-05-03 17:15:13.080
2021-05-03T17:15:13.0926187Z <EXPR>:0: error: TypealiasTests.testTypealiasDeclarationsWithGenericRequirement : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0928568Z Test Case 'TypealiasTests.testTypealiasDeclarationsWithGenericRequirement' failed (0.005 seconds)
2021-05-03T17:15:13.0929892Z Test Suite 'TypealiasTests' failed at 2021-05-03 17:15:13.085
2021-05-03T17:15:13.0930481Z 	 Executed 2 tests, with 2 failures (2 unexpected) in 0.006 (0.006) seconds
2021-05-03T17:15:13.0931057Z Test Suite 'VariableTests' started at 2021-05-03 17:15:13.085
2021-05-03T17:15:13.0931978Z Test Case 'VariableTests.testMultipleVariableDeclaration' started at 2021-05-03 17:15:13.085
2021-05-03T17:15:13.0933686Z <EXPR>:0: error: VariableTests.testMultipleVariableDeclaration : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0935371Z Test Case 'VariableTests.testMultipleVariableDeclaration' failed (0.0 seconds)
2021-05-03T17:15:13.0936606Z Test Case 'VariableTests.testTupleVariableDeclaration' started at 2021-05-03 17:15:13.086
2021-05-03T17:15:13.0938223Z <EXPR>:0: error: VariableTests.testTupleVariableDeclaration : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0939912Z Test Case 'VariableTests.testTupleVariableDeclaration' failed (0.0 seconds)
2021-05-03T17:15:13.0941342Z Test Case 'VariableTests.testVariableDeclarationWithTypeAnnotation' started at 2021-05-03 17:15:13.086
2021-05-03T17:15:13.0943428Z <EXPR>:0: error: VariableTests.testVariableDeclarationWithTypeAnnotation : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0945481Z Test Case 'VariableTests.testVariableDeclarationWithTypeAnnotation' failed (0.0 seconds)
2021-05-03T17:15:13.0947238Z Test Case 'VariableTests.testVariableDeclarationWithoutTypeAnnotation' started at 2021-05-03 17:15:13.086
2021-05-03T17:15:13.0949478Z <EXPR>:0: error: VariableTests.testVariableDeclarationWithoutTypeAnnotation : threw error "The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax"
2021-05-03T17:15:13.0951717Z Test Case 'VariableTests.testVariableDeclarationWithoutTypeAnnotation' failed (0.0 seconds)
2021-05-03T17:15:13.0952878Z Test Suite 'VariableTests' failed at 2021-05-03 17:15:13.086
2021-05-03T17:15:13.0953463Z 	 Executed 4 tests, with 4 failures (4 unexpected) in 0.0 (0.0) seconds
2021-05-03T17:15:13.0954018Z Test Suite 'debug.xctest' failed at 2021-05-03 17:15:13.086
2021-05-03T17:15:13.0954592Z 	 Executed 26 tests, with 26 failures (26 unexpected) in 0.006 (0.006) seconds
2021-05-03T17:15:13.0955138Z Test Suite 'All tests' failed at 2021-05-03 17:15:13.086
2021-05-03T17:15:13.0955675Z 	 Executed 26 tests, with 26 failures (26 unexpected) in 0.006 (0.006) seconds
```
The snapshot is currently incompatible with the top-of-tree swift-syntax.  We could pin to 4ae758ab85ed2a5d3e3e8b5050a8ce52179bd102 or wait until a new snapshot is tagged.

**Comment by mattt** [comment]
> The snapshot is currently incompatible with the top-of-tree swift-syntax. We could pin to 4ae758ab85ed2a5d3e3e8b5050a8ce52179bd102 or wait until a new snapshot is created.

@compnerd If a new snapshot expected sometime today or tomorrow, I think we should wait for that. That said, you're welcome to temporarily tag against that commit to get CI passing, in which case I can hold off on merging.

**Comment by compnerd** [comment]
I don't think that there is a guaranteed window for the next tag.  It is attempted nightly but anything that gets introduced can prevent the tagging.  The last one occurred ~2 weeks ago (as an example).  I think that tagging is likely the safer route to unblock ourselves.  I can double check if we can (accidentally get away with 5.4)

Edit: verified that 5.5 is required for the prebuilt `_InternalSwiftSyntaxParser` as I remembered.

**Comment by mattt** [comment]
@compnerd Oh, I didn't realize that nightly tags were so flakey. In that case, yeah — let's pin to a commit. It looks like CI is passing, so I'll go ahead and merge this now. Thanks!

**Pull request merged**
